# GitHub workflow for testing the entire build,
# including installation, the test suite and building of the docs.
name: build

on:
    schedule:
      - cron: '0 0 * * SUN'
    pull_request:
        branches:
          - master
        paths:
          - 'installer'
          - 'Dockerfile'

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
          - name: Checkout 🛎
            uses: actions/checkout@v2
          - name: Install 🔧
            run: docker build -t concept .
          - name: Test suite 🤖
            run: docker run concept concept -t all
          - name: Build docs 📖
            run: docker run concept make docs

